### ISSUE TITLE
ElasticSearch Documents Fix?

### ISSUE THREAD

**Issue by 0xOce** [x0e1f/dump-hub#7]
Each Elasticsearch shard is a Lucene index. The maximum number of documents you can have in a Lucene index is 2,147,483,519.

**Comment by suporte31** [comment]
What would be the best solution?

**Comment by x0e1f** [comment]
I think that the best solution in order to fix this issue is to increase the number of shards for the dump-hub index and play around with the docker-compose file in order to build a better performant and stable cluster (See this for more information: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html). Unfortunately I do not have enough hardware resources nor data to perform tests with very large data sets, but if anyone could test those use cases and provide feedback I'll be more than happy to accept suggestions and contributions.

Since my primary objective was to minimize disk usage I wrote a simple cluster configuration with a single node and no replica, but anyone could easily edit the project to fit his needs (see docker-compose.yml file and dump-hub/internal/esapi/share.go).

**Comment by suporte31** [comment]
Hi, I took the test so i'm notifying you.

**Comment by suporte31** [comment]
I used Amazon ElasticSearch Service. With multiple shards. I think the solution is to create an index for each file.

**Comment by x0e1f** [comment]
Sure, also this one could be an optimal soultion, that will also speed up document removal. I will try to implement it and perform some tests. If everything works fine and does not impact too much on disk usage and performance I will publish it on the next version and link it to this issue. Thank you!

**Comment by suporte31** [comment]
OK thanks

**Comment by x0e1f** [comment]
Issue should now be fixed with 98dfff5 (version 1.1.2). I leave this issue open for now in case you want to perform more tests and give feedback. Thank you for the interest and the good suggestion :)

**Comment by suporte31** [comment]
Hi, thanks for this update. 
I will be testing on AWS ES + EC2 VM.
